import BoxFinder from '@/components/main/BoxFinder';
import Case from '@/components/main/Case';
import Customers from '@/components/main/Customers';
import Cutomization from '@/components/main/Cutomization';
import Greens from '@/components/main/Greens';
import Header from '@/components/main/Header';
import Manufacturing from '@/components/main/Manufacturing';
import Navbar from '@/components/main/Navbar';
import Preview from '@/components/main/Preview';
import AnotherService from '@/components/main/another-service';
import Footer from '@/components/main/footer';
import Packaing from '@/components/main/packaging';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Packly-Lite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Header />
        <Customers />
        <section className="flex flex-col lg:gap-24 gap-12 lg:py-24 py-12">
          <Cutomization />
          <Preview />
          <AnotherService />
        </section>
        <BoxFinder />
        <Packaing />
        <Case />
        <Greens />
        <Manufacturing />
      </main>
      <Footer />
    </>
  );
}
